Fix userdata templates and add template restore cmd
When agent mode is enabled, the agent will manage the lifecycle of the
runner. We must make sure we do not also install the github runner service.

This change also adds the template restore cmd to the CLI.

Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>

diff --git a/internal/templates/userdata/gitea_linux_userdata.tmpl b/internal/templates/userdata/gitea_linux_userdata.tmpl
--- a/internal/templates/userdata/gitea_linux_userdata.tmpl
+++ b/internal/templates/userdata/gitea_linux_userdata.tmpl
@@ -185,24 +185,23 @@ getRunnerFile "system/service-name" ""$RUN_HOME"/.service" || fail "failed to ge
 sed -i 's/$/\.service/' "$RUN_HOME"/.service
 SVC_NAME=$(cat "$RUN_HOME"/.service)
 
-sendStatus "generating systemd unit file"
-getRunnerFile "systemd/unit-file?runAsUser={{ .RunnerUsername }}" "$SVC_NAME" || fail "failed to get service file"
-sudo mv $SVC_NAME /etc/systemd/system/ || fail "failed to move service file"
-sudo chown root:root /etc/systemd/system/$SVC_NAME || fail "failed to change owner"
-if [ -e "/sys/fs/selinux" ];then
-        sudo chcon -h system_u:object_r:systemd_unit_file_t:s0 /etc/systemd/system/$SVC_NAME || fail "failed to change selinux context"
-	sudo chcon -R -h user_u:object_r:bin_t:s0 /home/runner/ || fail "failed to change selinux context"
-fi
-
-sudo systemctl daemon-reload || fail "failed to reload systemd"
-
 AGENT_ID=""
 sendStatus "starting service"
 if [ "$AGENT_MODE" == "true" ]; then
     sendStatus "Enabling garm-agent service"
     sudo systemctl enable --now garm-agent
 else
-    sudo systemctl enable --now $SVC_NAME
+	sendStatus "generating systemd unit file"
+	getRunnerFile "systemd/unit-file?runAsUser={{ .RunnerUsername }}" "$SVC_NAME" || fail "failed to get service file"
+	sudo mv $SVC_NAME /etc/systemd/system/ || fail "failed to move service file"
+	sudo chown root:root /etc/systemd/system/$SVC_NAME || fail "failed to change owner"
+	if [ -e "/sys/fs/selinux" ];then
+		sudo chcon -h system_u:object_r:systemd_unit_file_t:s0 /etc/systemd/system/$SVC_NAME || fail "failed to change selinux context"
+		sudo chcon -R -h user_u:object_r:bin_t:s0 /home/runner/ || fail "failed to change selinux context"
+	fi
+
+	sudo systemctl daemon-reload || fail "failed to reload systemd"
+	sudo systemctl enable --now $SVC_NAME
 fi
 
 set +e
diff --git a/internal/templates/userdata/github_linux_userdata.tmpl b/internal/templates/userdata/github_linux_userdata.tmpl
--- a/internal/templates/userdata/github_linux_userdata.tmpl
+++ b/internal/templates/userdata/github_linux_userdata.tmpl
@@ -189,18 +189,20 @@ sed -i 's/$/\.service/' "$RUN_HOME"/.service
 
 SVC_NAME=$(cat "$RUN_HOME"/.service)
 
-sendStatus "generating systemd unit file"
-getRunnerFile "systemd/unit-file?runAsUser={{ .RunnerUsername }}" "$SVC_NAME" || fail "failed to get service file"
-sudo mv $SVC_NAME /etc/systemd/system/ || fail "failed to move service file"
-sudo chown root:root /etc/systemd/system/$SVC_NAME || fail "failed to change owner"
-if [ -e "/sys/fs/selinux" ];then
-	sudo chcon -h system_u:object_r:systemd_unit_file_t:s0 /etc/systemd/system/$SVC_NAME || fail "failed to change selinux context"
-fi
+if [ "$AGENT_MODE" != "true" ]; then
+	sendStatus "generating systemd unit file"
+	getRunnerFile "systemd/unit-file?runAsUser={{ .RunnerUsername }}" "$SVC_NAME" || fail "failed to get service file"
+	sudo mv $SVC_NAME /etc/systemd/system/ || fail "failed to move service file"
+	sudo chown root:root /etc/systemd/system/$SVC_NAME || fail "failed to change owner"
+	if [ -e "/sys/fs/selinux" ];then
+		sudo chcon -h system_u:object_r:systemd_unit_file_t:s0 /etc/systemd/system/$SVC_NAME || fail "failed to change selinux context"
+	fi
 
-sendStatus "enabling runner service"
-cp "$RUN_HOME"/bin/runsvc.sh "$RUN_HOME"/ || fail "failed to copy runsvc.sh"
-sudo systemctl daemon-reload || fail "failed to reload systemd"
-sudo systemctl enable $SVC_NAME
+	sendStatus "enabling runner service"
+	cp "$RUN_HOME"/bin/runsvc.sh "$RUN_HOME"/ || fail "failed to copy runsvc.sh"
+	sudo systemctl daemon-reload || fail "failed to reload systemd"
+	sudo systemctl enable $SVC_NAME
+fi
 {{- else}}
 
 GITHUB_TOKEN=$(curl --retry 5 --retry-delay 5 --retry-connrefused --fail -s -X GET -H 'Accept: application/json' -H "Authorization: Bearer ${BEARER_TOKEN}" "${METADATA_URL}/runner-registration-token/")
