Add agent mode
This change adds a new "agent mode" to GARM. The agent enables GARM to
set up a persistent websocket connection between the garm server and the
runners it spawns. The goal is to be able to easier keep track of state,
even without subsequent webhooks from the forge.

The Agent will report via websockets when the runner is actually online,
when it started a job and when it finished a job.

Additionally, the agent allows us to enable optional remote shell between
the user and any runner that is spun up using agent mode. The remote shell
is multiplexed over the same persistent websocket connection the agent
sets up with the server (the agent never listens on a port).

Enablement has also been done in the web UI for this functionality.

Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>

diff --git a/internal/templates/userdata/github_linux_userdata.tmpl b/internal/templates/userdata/github_linux_userdata.tmpl
--- a/internal/templates/userdata/github_linux_userdata.tmpl
+++ b/internal/templates/userdata/github_linux_userdata.tmpl
@@ -2,14 +2,23 @@
 
 set -e
 set -o pipefail
+set -x
 
 {{- if .EnableBootDebug }}
 set -x
 {{- end }}
 
+# Edit the templates directly in the browser. Intellisense is available for golang templates
+# {{ .DownloadURL }}
+
 CALLBACK_URL="{{ .CallbackURL }}"
 METADATA_URL="{{ .MetadataURL }}"
 BEARER_TOKEN="{{ .CallbackToken }}"
+
+# touch /tmp/hold
+# while true;do
+#    [ -e /tmp/hold ] && sleep 2 || break
+# done
 
 RUN_HOME="/home/{{ .RunnerUsername }}/actions-runner"
 
@@ -54,6 +63,80 @@ function fail() {
 	call "{\"status\": \"failed\", \"message\": \"$MSG\"}"
 	exit 1
 }
+
+INSTANCE_METADATA=$(curl \
+    --retry 5 \
+    --retry-delay 5 \
+    --retry-connrefused \
+    --fail -s \
+    -H 'Accept: application/json' \
+    -H "Authorization: Bearer ${BEARER_TOKEN}" \
+    "$METADATA_URL/runner-metadata" 2>&1) || fail "failed to get instance metadata: $INSTANCE_METADATA"
+
+AGENT_MODE=$(echo "$INSTANCE_METADATA" | jq -r '.agent_mode // empty')
+if [ "$AGENT_MODE" == "true" ]; then
+    sendStatus "Agent mode is enabled; setting up agent"
+    DOWNLOAD_URL=$(echo "$INSTANCE_METADATA" | jq -r '.agent_tools.download_url // empty')
+    if [ -z "$DOWNLOAD_URL" ]; then
+        fail "agent mode is enabled, but no agent tools found in metadata"
+    fi
+    AGENT_URL=$(echo "$INSTANCE_METADATA" | jq -r '.metadata_access.agent_url // empty')
+    if [ -z "$AGENT_URL" ]; then
+        fail "agent mode is enabled, but agent_url was not found in metadata"
+    fi
+    AGENT_TOKEN=$(echo "$INSTANCE_METADATA" | jq -r '.agent_token // empty')
+    if [ -z "$AGENT_TOKEN" ]; then
+        fail "agent mode is enabled, but agent_token was not found in metadata"
+    fi
+    AGENT_SHELL=$(echo "$INSTANCE_METADATA" | jq -r '.agent_shell_enabled // false')
+    sendStatus "Downloading agent from $DOWNLOAD_URL"
+    sudo curl --retry 5 \
+        --retry-delay 5 \
+        --retry-connrefused \
+        --fail -L \
+        -H "Authorization: Bearer ${BEARER_TOKEN}" \
+        -o /usr/local/bin/garm-agent "$DOWNLOAD_URL" || fail "failed to download garm-agent"
+    sudo chmod +x /usr/local/bin/garm-agent || fail "failed to make garm-agent executable"
+    sudo mkdir -p /var/log/garm-agent || fail "failed to create /var/log/garm-agent"
+    sudo chown {{ .RunnerUsername }}:{{ .RunnerUsername }} /var/log/garm-agent || fail "failed to chown /var/log/garm-agent"
+    sudo mkdir -p /etc/garm-agent || fail "failed to create /etc/garm"
+    sudo chown {{ .RunnerUsername }}:{{ .RunnerUsername }} /etc/garm-agent || fail "failed to change owner on /etc/garm-agent"
+
+    sendStatus "Creating config and systemd unit"
+    cat > /etc/garm-agent/garm-agent.toml << EOF
+server_url = "$AGENT_URL"
+log_file = "/var/log/garm-agent/garm-agent.log"
+work_dir = "$RUN_HOME"
+enable_shell = $AGENT_SHELL
+token = "$AGENT_TOKEN"
+runner_cmdline = ["/bin/bash", "-C", "/home/runner/actions-runner/run.sh"]
+state_db_path = "/etc/garm-agent/agent-state.db"
+EOF
+
+    cat > /tmp/garm-agent.service << EOF
+[Unit]
+Description=GARM agent
+After=multi-user.target
+
+[Service]
+Type=simple
+ExecStart=/usr/local/bin/garm-agent daemon --config /etc/garm-agent/garm-agent.toml
+ExecReload=/bin/kill -HUP $MAINPID
+Restart=always
+RestartSec=5s
+User={{ .RunnerUsername }}
+Environment=TERM=xterm-256color
+Environment=LANG=en_US.UTF-8
+
+[Install]
+WantedBy=multi-user.target
+EOF
+
+    sudo mv /tmp/garm-agent.service /etc/systemd/system/garm-agent.service || fail "failed to create /etc/systemd/system/garm-agent.service"
+    sudo chown root:root /etc/systemd/system/garm-agent.service || fail "failed to change owner on /etc/systemd/system/garm-agent.service"
+    sendStatus "Reloading systemd unit"
+    sudo systemctl daemon-reload || fail "failed to reload systemd"
+fi
 
 function downloadAndExtractRunner() {
 	sendStatus "downloading tools from {{ .DownloadURL }}"
@@ -116,13 +199,12 @@ fi
 
 sendStatus "enabling runner service"
 cp "$RUN_HOME"/bin/runsvc.sh "$RUN_HOME"/ || fail "failed to copy runsvc.sh"
-# Chown is not needed for the cached runner
-# sudo chown {{ .RunnerUsername }}:{{ .RunnerGroup }} -R /home/{{ .RunnerUsername }} || fail "failed to change owner"
 sudo systemctl daemon-reload || fail "failed to reload systemd"
 sudo systemctl enable $SVC_NAME
 {{- else}}
 
 GITHUB_TOKEN=$(curl --retry 5 --retry-delay 5 --retry-connrefused --fail -s -X GET -H 'Accept: application/json' -H "Authorization: Bearer ${BEARER_TOKEN}" "${METADATA_URL}/runner-registration-token/")
+
 
 set +e
 attempt=1
@@ -172,10 +254,14 @@ if [ -f "$RUN_HOME/env.sh" ];then
 	source env.sh
 	popd
 fi
-sudo systemctl start $SVC_NAME || fail "failed to start service"
+if [ "$AGENT_MODE" != "true" ]; then
+    sudo systemctl start $SVC_NAME || fail "failed to start service"
+fi
 {{- else}}
-sendStatus "starting service"
-sudo ./svc.sh start || fail "failed to start service"
+if [ "$AGENT_MODE" != "true" ]; then
+    sendStatus "starting service"
+    sudo ./svc.sh start || fail "failed to start service"
+fi
 
 set +e
 AGENT_ID=$(grep "agentId" "$RUN_HOME"/.runner |  tr -d -c 0-9)
@@ -185,4 +271,8 @@ fi
 set -e
 {{- end}}
 systemInfo $AGENT_ID
+if [ "$AGENT_MODE" == "true" ]; then
+  sendStatus "Starting garm-agent service"
+  sudo systemctl enable --now garm-agent || sendStatus "failed to start garm-agent"
+fi
 success "runner successfully installed" $AGENT_ID
